#!/usr/bin/env python3
"""
从 src/binds 目录中提取所有 Lua 绑定函数名
用于 REPL 自动补全
"""

import re
import os
from pathlib import Path

def extract_functions_from_file(filepath):
    """从单个 C++ 文件中提取 Lua 绑定的函数名"""
    functions = []
    
    with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()
    
    # 匹配 .addFunction("functionName", ...)
    function_pattern = r'\.addFunction\s*\(\s*"([^"]+)"'
    functions.extend(re.findall(function_pattern, content))
    
    # 匹配 .addVariable("varName", ...)
    variable_pattern = r'\.addVariable\s*\(\s*"([^"]+)"'
    functions.extend(re.findall(variable_pattern, content))
    
    # 匹配 namespace 名称 .beginNamespace("name")
    namespace_pattern = r'\.beginNamespace\s*\(\s*"([^"]+)"\)'
    namespaces = re.findall(namespace_pattern, content)
    
    # 为 namespace 中的函数添加前缀
    namespace_functions = []
    for ns in namespaces:
        # 查找该 namespace 块中的函数
        ns_block_pattern = rf'\.beginNamespace\s*\(\s*"{ns}"\s*\)(.*?)\.endNamespace\s*\(\s*\)'
        ns_blocks = re.findall(ns_block_pattern, content, re.DOTALL)
        
        for block in ns_blocks:
            ns_funcs = re.findall(r'\.addFunction\s*\(\s*"([^"]+)"', block)
            for func in ns_funcs:
                namespace_functions.append(f"{ns}.{func}")
    
    functions.extend(namespace_functions)
    
    return list(set(functions))  # 去重

def extract_all_functions(binds_dir):
    """从所有绑定文件中提取函数"""
    all_functions = []
    
    binds_path = Path(binds_dir)
    
    # 遍历所有 .cpp 文件
    for cpp_file in binds_path.rglob('*.cpp'):
        try:
            funcs = extract_functions_from_file(cpp_file)
            if funcs:
                all_functions.extend(funcs)
                print(f"[+] {cpp_file.name}: {len(funcs)} functions")
        except Exception as e:
            print(f"[!] Error processing {cpp_file}: {e}")
    
    return sorted(list(set(all_functions)))

def generate_cpp_header(functions, output_file):
    """生成 C++ 头文件"""
    
    header_content = f"""// Auto-generated file - DO NOT EDIT
// Generated by tools/extract_lua_functions.py
// Total functions: {len(functions)}

#ifndef LUA_FUNCTION_LIST_H
#define LUA_FUNCTION_LIST_H

#include <vector>
#include <string>

inline std::vector<std::string> getCustomLuaFunctions() {{
    return {{
"""
    
    for func in functions:
        header_content += f'        "{func}",\n'
    
    header_content += """    };
}

#endif // LUA_FUNCTION_LIST_H
"""
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(header_content)
    
    print(f"\n[*] Generated {output_file} with {len(functions)} functions")

if __name__ == "__main__":
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    binds_dir = project_root / "src" / "binds"
    output_file = project_root / "src" / "include" / "lua_function_list.h"
    
    print(f"[*] Extracting Lua functions from {binds_dir}")
    functions = extract_all_functions(binds_dir)
    
    print(f"\n[*] Total unique functions found: {len(functions)}")
    
    generate_cpp_header(functions, output_file)
    
    print("\n[*] Done! Include this header in repl_manager.cpp")
